### ISSUE TITLE
Does it support react native?

### ISSUE THREAD

**Issue by sh4msi** [Kiarash-Z/react-persian-calendar-date-picker#40] opened 2019-10-16 12:34 UTC
hi
Does it support react native?

**Comment by thebrodmann** [comment] 2019-10-16 18:22
Duplicate of #25

**Comment by Kiarash-Z** [comment] 2019-10-19 05:40
Hi @sh4msi. You can use [This package](http://bit.ly/react-native-modern-datepicker)

**Closed by Kiarash-Z** 2019-10-19 05:40 UTC
